#!/usr/bin/env bash
# https://unix.stackexchange.com/a/87763/
LC_ALL=C

# Should be kept in sync with https://github.com/6RiverSystems/rush-monorepo-boilerplate/blob/main/common/git-hooks/pre-push
valid_branch_regex='^[a-z0-9_./\\-]*$'

# Symbolic value that represents "the all-zeroes object name" (copied from .git/hooks/pre-push.sample)
zero="$(git hash-object --stdin </dev/null | tr '0-9a-f' '0')"

# Copied from .git/hooks/pre-push.sample
# shellcheck disable=SC2034
while read -r local_ref local_oid remote_ref remote_oid; do
	# New branch or update to existing branch, validate branch name
	if [ "$local_oid" != "$zero" ]; then
		branch_name="${local_ref#refs/heads/}"

		# Special case to support pushing the current branch without naming it
		if [ "$branch_name" = "HEAD" ]; then
			exit 0
		fi

		if ! [[ $branch_name =~ $valid_branch_regex ]]; then
			echo >&2 "Error: push aborted because branch name \"$branch_name\" contains invalid characters"
			echo >&2 "Branch names may only contain lowercase letters, numbers, periods, dashes, underscores, and forward slashes."
			exit 1
		fi
	fi
done

exit 0
