version: 2.1

orbs:
  sixrs-gke: sixriversystems/sixrs-gke@7

aliases:
  - &node_image cimg/node:16.19.1

jobs:
  setup:
    docker:
      - image: *node_image
    steps:
      - checkout
      - sixrs-gke/setup-private-npm
      - run:
          name: Install Dependencies
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - .
  test:
    docker:
      - image: *node_image
    environment:
      MOCHA_OPTS: --reporter mocha-junit-reporter --reporter-options mochaFile=./reports/junit/mocha/mocha.xml
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: Unit Tests
          command: npm run test
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports
  publish:
    docker:
      - image: *node_image
    steps:
      - attach_workspace:
          at: ./
      - sixrs-gke/run-release
      - sixrs-gke/npm-public-publish
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - setup:
          context: 6rs-circle
      - test:
          context: 6rs-public-npm
          requires:
            - setup
      - publish:
          context: 6rs-public-npm
          requires:
            - setup
            - test
          filters:
            branches:
              only: master
